//LANDS
export const SET_LANDS = 'SET_LANDS';
export const SET_PLAYLIST = 'SET_PLAYLIST';

// TRACKS
export const SET_TRACK = 'SET_TRACK';
export const SET_TRACK_DURATION = 'SET_TRACK_DURATION';
export const SET_TRACK_CURRENT_TIME = 'SET_TRACK_CURRENT_TIME';

//CONTROLS
export const PLAY_TRACK = 'PLAY_TRACK';
export const PAUSE_TRACK = 'PAUSE_TRACK';
export const INFINITE_PLAY = 'INFINITE_PLAY';
export const SHUFFLE_PLAY = 'SHUFFLE_PLAY';
